// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package forms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Login() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"/login\" hx-encoding=\"multipart/form-data\" class=\"\"><div class=\"grid grid-cols-1 md:grid-cols-2  gap-4 mt-5\"><div class=\"md:col-span-1\"><label for=\"email\" class=\"quote-form-label\">Email</label> <input type=\"email\" required name=\"email\" id=\"email\" placeholder=\"email\" class=\"quote-form-field\"></div><div class=\"md:col-span-1\"><label for=\"password\" class=\"quote-form-label\">Password</label> <input type=\"password\" required id=\"password\" name=\"password\" placeholder=\"password\" class=\"quote-form-field\"></div></div><div class=\"mt-4\"><button type=\"submit\" class=\"inline-flex justify-center w-full py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500\">Login</button></div></form><div class=\"mt-5 p-2\">Don't have an account?  <button type=\"button\" class=\"text-blue-700\" hx-get=\"/auth/signup\" hx-target=\"#view\" hx-trigger=\"click\" hx-push-url=\"true\">Create one</button></div><div class=\"p-1\" hx-on:click=\"toggleItt()\"><button type=\"button\" class=\"text-blue-700\">Forgot Password? </button></div><div class=\"mt-4 hidden\" id=\"emailInputContainer\"><form hx-post=\"/passreset\" hx-encoding=\"multipart/form-data\" hx-indicator=\"#reset-indicator\"><div class=\"md:col-span-1\"><label for=\"email\" class=\"quote-form-label\">Enter your email</label> <input type=\"email\" name=\"email\" placeholder=\"Email\" class=\"quote-form-field\" required></div><button type=\"submit\" class=\"mt-2  text-blue-700 bg-gray-200 rounded p-2\">Reset</button></form><div class=\"htmx-indicator px-2\" id=\"reset-indicator\">Please wait...</div></div><script>\n\t\tfunction toggleItt(){\n\t\t\tdocument.getElementById(\"emailInputContainer\").classList.toggle(\"hidden\")\n\t\t}\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
