// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package forms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/xnpltn/hcc/internal/models"
import "fmt"

func RevieForm(service models.Service) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form class=\"hidden\" id=\"review-form\" hx-vals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(fmt.Sprintf(`{"serviceID":"%s"}`, service.ID)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-post=\"/review\" hx-encoding=\"multipart/form-data\" hx-trigger=\"submit\" hx-indicator=\"#loading\"><div class=\"mb-4\"><label for=\"review\" class=\"block text-gray-700 font-bold mb-2\">Review</label> <textarea id=\"review\" name=\"review\" class=\"w-full border border-gray-300 rounded-md p-2\" rows=\"4\" maxlength=\"100\" minlength=\"60\" required></textarea></div><div class=\"mb-4\"><label for=\"rating\" class=\"block text-gray-700 font-bold mb-2\">Rating</label><div class=\"flex items-center\"><input type=\"radio\" name=\"rating\" id=\"rating-1\" value=\"1\" class=\"mr-2\" required> <label for=\"rating-1\" class=\"text-yellow-500\">&#9733;</label> <input type=\"radio\" name=\"rating\" id=\"rating-2\" value=\"2\" class=\"mx-2\"> <label for=\"rating-2\" class=\"text-yellow-500\">&#9733;&#9733;</label> <input type=\"radio\" name=\"rating\" id=\"rating-3\" value=\"3\" class=\"mx-2\"> <label for=\"rating-3\" class=\"text-yellow-500\">&#9733;&#9733;&#9733;</label> <input type=\"radio\" name=\"rating\" id=\"rating-4\" value=\"4\" class=\"mx-2\"> <label for=\"rating-4\" class=\"text-yellow-500\">&#9733;&#9733;&#9733;&#9733;</label> <input type=\"radio\" name=\"rating\" id=\"rating-5\" value=\"5\" class=\"mx-2\"> <label for=\"rating-5\" class=\"text-yellow-500\">&#9733;&#9733;&#9733;&#9733;&#9733;</label></div></div><button type=\"submit\" class=\"bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 transition-colors\">Submit Review</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
