// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/xnpltn/hcc/internal/models"
import "github.com/xnpltn/hcc/internal/templates/forms"

func ProfilePage(user models.User) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>HCC | Profile</title><link rel=\"shortcut icon\" href=\"/static/images/logo.svg\" type=\"image/x-icon\"><link href=\"/static/css/styles.css\" rel=\"stylesheet\"><script src=\"/static/js/app.js\" defer></script><script src=\"/static/js/htmx.min.js\" defer></script><link href=\"/static/css/custom.css\" rel=\"stylesheet\"></head><body class=\"px-5 pb-10\"><header class=\"py-4 px-4 flex justify-center items-center\"><div class=\"container mx-auto flex justify-center flex-col items-center\"><img src=\"/static/images/logo.svg\" class=\"h-32 w-32 rounded bg-blue-900\"><h3 class=\"mt-2 text-lg md:text-xl font-bold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("@happycloudcomputing")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/profile.templ`, Line: 22, Col: 75}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h3></div></header><main><section class=\"flex flex-col items-center gap-5\"><div class=\"bg-gray-600 w-64 flex flex-col items-center py-3 rounded-md\"><h3 class=\"text-white py-2 capitalize font-semibold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(user.Name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/profile.templ`, Line: 28, Col: 69}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h3><div class=\"flex flex-col items-center justify-center h-full\"><img class=\"rounded-full w-16 h-16 mb-2\" src=\"/static/images/placeholder-img.jpg\" alt=\"User Avatar\"><h2 class=\"text-lg  text-white mb-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(user.Username)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/profile.templ`, Line: 36, Col: 23}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h2><p class=\"text-sm text-gray-200\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(user.Email)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/profile.templ`, Line: 39, Col: 20}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div></div><div><div class=\"flex items-center flex-col mb-5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !user.Verified {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"text-center mb-2 cursor-pointer\" hx-get=\"/auth/verify\" hx-trigger=\"click\" hx-swap=\"outerHTML\" hx-indicator=\"#verify-indicator\"><span type=\"button\" class=\" bg-blue-700 rounded-md p-2 text-white\">Verify email</span><div class=\"htmx-indicator\" id=\"verify-indicator\">Please wait...</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex items-center justify-center text-center\"><button type=\"button\" class=\" bg-red-700 rounded-md p-2 text-white\" hx-get=\"/logout\" hx-confirm=\"Are you sure you want to logout?\">Logout</button></div></div><div class=\"flex items-center justify-center text-center mb-5\"><button type=\"button\" class=\"text-blue-700 rounded bg-gray-200 p-2\" hx-on:click=\"toggleProfileUpdateForm()\">Update Profile</button></div><div class=\"hidden\" id=\"update-form-container\"><h3 class=\"text-center text-2xl font-bold\">Update Profile</h3><p class=\"text-blue-700 text-sm text-center\">Leave it empty if you don't want to make changes</p><div id=\"content_div\" class=\" max-w-md\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = forms.UpdateProfileForm(user).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div></section><script>\n\t\t\t\t\tfunction toggleProfileUpdateForm(){\n\t\t\t\t\t\tdocument.getElementById(\"update-form-container\").classList.toggle(\"hidden\")\n\t\t\t\t\t}\n\t\t\t\t</script></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
