// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/xnpltn/hcc/internal/models"

func success() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_success_6fa3`,
		Function: `function __templ_success_6fa3(){document.addEventListener("DOMContentLoaded", async () => {
    const { publishableKey } = await fetch("/config").then(r => r.json())
    const stripe = Stripe(publishableKey)
    const params = new URLSearchParams(window.location.href)
    const clientSecret = params.get("payment_intent_client_secret")
    const { paymentIntent } = await stripe.retrievePaymentIntent(clientSecret)
    const per = document.getElementById("description")
    // per.innerText = JSON.stringify(paymentIntent, null, 2)
	per.innerText = paymentIntent.description
})
}`,
		Call:       templ.SafeScript(`__templ_success_6fa3`),
		CallInline: templ.SafeScriptInline(`__templ_success_6fa3`),
	}
}

func SuccessPage(_ models.User) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>HCC | Succesfull Payment</title><link rel=\"shortcut icon\" href=\"/static/images/logo.svg\" type=\"image/x-icon\"><link href=\"/static/css/styles.css\" rel=\"stylesheet\"><script src=\"/static/js/app.js\" defer></script><script src=\"/static/js/htmx.min.js\" defer></script><link href=\"/static/css/custom.css\" rel=\"stylesheet\"><link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\"><script src=\"https://js.stripe.com/v3/\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = success().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</head><body class=\"px-5\"><header class=\"py-4 px-4 flex justify-center items-center\"><div class=\"container mx-auto flex justify-center flex-col items-center\"><img src=\"/static/images/logo.svg\" class=\"h-32 w-32 rounded bg-blue-900\"><h3 class=\"mt-2 text-lg md:text-xl font-bold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("@happycloudcomputing")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/pages/success.templ`, Line: 40, Col: 75}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h3></div></header><section class=\"flex flex-col items-center\"><div class=\"flex items-center justify-center h-32\"><div class=\"p-2 flex items-center justify-center h-full flex-col text-center\"><h1 class=\"text-red-300 font-bold text-lg\">Completed successfully</h1><div id=\"payment-intent\"><p id=\"description\" class=\"max-w-sm\"></p><span class=\"material-symbols-outlined w-32 \">check</span></div></div></div></section></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
