// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package modals

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/xnpltn/hcc/internal/models"
import "strings"

func ConsultationModal(activeTimes []models.ActiveHours) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"modal hidden fixed inset-0 bg-gray-900 bg-opacity-50 flex items-center justify-center\" id=\"modal-3\"><div class=\"modal-content bg-white rounded-lg max-w-4xl w-full md:min-w-[720px] max-h-[80vh] flex flex-col\"><div class=\"flex justify-between items-center bg-gray-100 px-4 py-2 rounded-t-lg border-b border-gray-500 bg-slate-300\"><h2 class=\"text-xl font-bold\">Appointment</h2><span class=\"material-symbols-outlined close-modal cursor-pointer text-gray-500 hover:text-gray-800\">close</span></div><div class=\"p-4 overflow-y-auto flex-grow\"><div><form class=\"max-w-3xl mx-auto\" hx-encoding=\"multipart/form-data\" hx-post=\"/appointment\" hx-trigger=\"submit\" hx-indicator=\".htmx-indicator\"><div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><div class=\"md:col-span-1\"><label for=\"name\" class=\"quote-form-label\">Name</label> <input type=\"text\" id=\"name\" name=\"name\" class=\"quote-form-field\"></div><div class=\"md:col-span-1\"><label for=\"email\" class=\"quote-form-label\">Email</label> <input type=\"email\" name=\"email\" id=\"email\" class=\"quote-form-field\"></div><div class=\"md:col-span-1\"><label for=\"free\" class=\"quote-form-label\">Free </label> <select class=\"quote-form-field\" id=\"free\" name=\"free\"><option value=\"0\">No</option> <option value=\"1\">Yes</option></select></div><div class=\"md:col-span-1\"><label for=\"date\" class=\"quote-form-label\">Choose Date and Time</label> <select class=\"quote-form-field\" id=\"date\" name=\"date\"><option value=\"\">Choose</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, act := range activeTimes {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(strings.Split(act.Active, ":00.000Z")[0]))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(strings.Split(act.Active, ":00.000Z")[0])
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/modals/consultation_modal.templ`, Line: 42, Col: 109}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" UTC</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</select></div></div><div class=\"mt-4\"><button type=\"submit\" class=\"inline-flex justify-center w-full py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500\">Submit</button></div></form></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
