// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Footer() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"bg-white rounded-lg shadow dark:bg-gray-900 m-4\"><div class=\"w-full max-w-screen-xl mx-auto p-4 md:py-8\"><div class=\"sm:flex sm:items-center sm:justify-between\"><a href=\"https://flowbite.com/\" class=\"flex items-center mb-4 sm:mb-0 space-x-3 rtl:space-x-reverse\"><span class=\"self-center text-2xl font-semibold whitespace-nowrap dark:text-white\">HCC</span></a><ul class=\"flex flex-wrap items-center mb-6 text-sm font-medium text-gray-500 sm:mb-0 dark:text-gray-400\"><li><a href=\"#\" class=\"hover:underline me-4 md:me-6\">Privacy Policy</a></li><li><a href=\"#\" class=\"hover:underline me-4 md:me-6\">Blog</a></li><li><a href=\"#\" class=\"hover:underline\">Contect us</a></li></ul></div><hr class=\"my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8\"><span class=\"block text-sm text-gray-500 sm:text-center dark:text-gray-400\">© 2024 <a href=\"/\" class=\"hover:underline\">HCC™</a>. All Rights Reserved.</span></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
