// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/xnpltn/hcc/internal/templates/components"

func About() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"hidden transition-all duration-300\" id=\"about_section\"><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 p-1 bg-gradient-to-r from-purple-950 to-blue-950 rounded-lg m-10 p-4\"><div class=\"flex flex-col items-center\"><h2 class=\"text-lg text-white font-bold\">Core Offerings</h2><div class=\"mt-5 flex flex-col gap-5 \">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AboutCard("AWS Infrastructure Setup & Management", "Design, deploy, and manage scalable, secure, and cost-effective AWS infrastructure.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AboutCard("Serverless Architecture Consulting", "Build scalable and cost-effective applications using AWS Lambda, API Gateway, and more.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AboutCard("Cloud Migration Services", "Migrate applications and services to AWS with minimal downtime and a smooth transition.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div class=\"flex flex-col items-center\"><h1 class=\"text-lg text-white font-bold\">Specialized Services</h1><div class=\"mt-5 flex flex-col gap-5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AboutCard("AWS Cost Optimization", "Analyze and reduce AWS spending with cost-saving strategies.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AboutCard("Infrastructure as Code (IaC)", "Implement AWS CloudFormation or Terraform for efficient infrastructure management.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AboutCard("DevOps & CI/CD Pipeline Implementation", "Set up automated deployment pipelines using AWS CodePipeline, CodeBuild, and CodeDeploy for efficient application development and deployment.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div class=\"flex flex-col items-center\"><h1 class=\"text-lg text-white font-bold\">Additional Services</h1><div class=\"mt-5 flex flex-col gap-5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AboutCard("Data Migration & Analytics", "Assist clients in migrating their data to AWS data stores like Amazon S3, Amazon RDS, or Amazon DynamoDB, and provide data analytics services using AWS tools like Amazon Redshift, Amazon Athena, and Amazon QuickSight.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AboutCard("IoT & Edge Computing Solutions", "Build IoT solutions using AWS IoT Core, IoT Greengrass, and other services.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.AboutCard("Blockchain and Distributed Ledger Technology", "Explore decentralized and secure transaction systems using AWS blockchain services.").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
