// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.598
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/xnpltn/hcc/internal/models"

import "github.com/xnpltn/hcc/internal/templates/components"

func FaqView(faqs []models.FAQ) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"bg-white\"><div class=\"py-3 px-4 mx-auto max-w-screen-xl text-center\"><h1 class=\"mb-2 text-2xl font-extrabold tracking-tight leading-none  md:text-5xl lg:text-3xl text-gray-900\">FAQ</h1></div></section><section class=\"bg-white \"><div id=\"faqs\" class=\"py-3 px-4 mx-auto max-w-screen-xl text-center lg:py-5 grid grid-cols-1 gap-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, faq := range faqs {
			templ_7745c5c3_Err = components.FaqCard(faq).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></section><div><p class=\"text-center\">Need specific information ? <button type=\"button\" class=\" text-blue-700 ml-1\" id=\"faq-form-but\">Send Us a Message</button></p><div class=\"hidden\" id=\"quote-form-container\"><form class=\"max-w-3xl mx-auto\" hx-encoding=\"multipart/form-data\" hx-post=\"/faqs\" hx-trigger=\"submit\" hx-indicator=\".htmx-indicator\"><div class=\"md:col-span-1\"><label for=\"email\" class=\"quote-form-label\">Email</label> <input type=\"email\" id=\"email\" name=\"email\" class=\"quote-form-field\"></div><div class=\"md:col-span-2\"><label for=\"message\" class=\"quote-form-label\">Message</label> <textarea id=\"message\" rows=\"4\" name=\"message\" class=\"quote-form-field\"></textarea></div><div class=\"htmx-indicator py-1 px-2\">Sending .....</div><div class=\"mt-4\"><button type=\"submit\" class=\"inline-flex justify-center w-full py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500\">Submit</button></div></form></div></div><script>\n\t\tconst faqItems = document.querySelectorAll('#faqs > div');\n\n        const toggleFormBut = document.querySelector(\"#faq-form-but\")\n        const formContainer = document.querySelector(\"#quote-form-container\")\n        toggleFormBut.addEventListener(\"click\", ()=>{\n            formContainer.classList.toggle('hidden');\n        })\n\n\t\tfaqItems.forEach(item => {\n\t\tconst question = item.querySelector('div:first-child');\n\t\tconst answer = item.querySelector('div:last-child');\n\t\tconst icon = question.querySelector('span');\n\n\t\tquestion.addEventListener('click', () => {\n\t\t\tanswer.classList.toggle('hidden');\n\t\t\ticon.textContent = answer.classList.contains('hidden') ? 'expand_more' : 'expand_less';\n\t\t});\n\t\t});\n\t\t\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
